export const screenUrl = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  ANIME_DETAILS: '/anime/details/:title',
  WATCH_ANIME: '/watch-anime/:title/episode/:epValue',
  SEARCH: '/anime/search',
  HISTORY: '/history',
  CONTACT: '/contact',
  OUR_AGENT: '/our-agent',
  PROPERTY: '/property',
  CAREERS: '/careers',
  PRICING: '/pricing',
  PRESS: '/press',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_SERVICES: '/terms-services',
  SECURITY: '/security',
  BECOME_HOST: '/become-host',
};
